### ISSUE TITLE
Question about ndn_data_* API

### ISSUE THREAD

**Issue by astralien3000** [named-data-iot/ndn-riot#6]
Is it normal that we create a ndn_data packet with the "raw content" (using `ndn_data_create`), and we get a TLV-encoded content back with `ndn_data_get_content` ?
This behaviour is not symetric.
Is there a simple way to get rid of the TLV header returned ?

**Comment by wentaoshang** [comment]
Sorry for the late response. This is a good question. I think it makes sense to change `ndn_data_get_content` to return the raw content directly. Another choice would be to provide a generic helper function to parse the TLV block.

**Comment by astralien3000** [comment]
I think the "clean" way to do this, is to return the raw content directly. But it would change your API and maybe it is a problem if some projects use it ?
And anyway it may also be a good thing to have an API to manipulate easily TLV blocks ?
